
services:
###> doctrine/doctrine-bundle ###
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-crm_db}
      POSTGRES_USER: ${POSTGRES_USER:-crm_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-crm_pass}
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-crm_db}", "-U", "${POSTGRES_USER:-crm_user}"]
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###
  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "pgsql://${POSTGRES_USER:-crm_user}:${POSTGRES_PASSWORD:-crm_pass}@postgres:5432/${POSTGRES_DB:-crm_db}"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
###> doctrine/doctrine-bundle ###
  pgdata:
###< doctrine/doctrine-bundle ###
