apiVersion: apps/v1
kind: Deployment
metadata:
  name: crm-backend
  namespace: crm-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crm-backend
  template:
    metadata:
      labels:
        app: crm-backend
    spec:
      containers:
        - name: backend
          image: crm-backend:latest
          env:
            - name: DATABASE_URL
              value: pgsql://crm_user:crm_pass@postgres.crm-dev:5432/crm_db
          ports:
            - containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: crm-backend
  namespace: crm-dev
spec:
  selector:
    app: crm-backend
  ports:
    - port: 9000
      targetPort: 9000
